<?php

namespace Bo\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitCategorieRepository extends EntityRepository
{
}